# Generated by Django 3.1.4 on 2020-12-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, default='', upload_to='course\\img')),
                ('price', models.IntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('date_beginnings', models.DateField()),
                ('date_endings', models.DateField()),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'товари',
                'db_table': 'course',
            },
        ),
    ]
